### ISSUE TITLE
An exception of type MissingMethodException has been encountered

### ISSUE THREAD

**Issue by isral** [deviousasti/fsharp-linting-for-vs#5]
I just installed F# Lint 0.4.1 on VS 2019 16.8.0
```
System.MissingMethodException: Method not found: 'ParserResult`2<!!0,Microsoft.FSharp.Core.Unit> FParsec.CharParsers.run(Microsoft.FSharp.Core.FSharpFunc`2<FParsec.CharStream`1<Microsoft.FSharp.Core.Unit>,FParsec.Reply`1<!!0>>, System.String)'.
   at FSharpLint.Framework.Configuration.parseHint@548(String hint)
   at FSharpLint.Framework.Configuration.parseHints(String[] hints)
   at FSharpLint.Framework.Configuration.deprecatedAllRules@566-3.Invoke(HintConfig config)
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\option.fs:line 53
   at FSharpLint.Framework.Configuration.flattenConfig(Configuration config)
   at FSharpLint.Application.Lint.lint(LintInfo lintInfo, FileParseInfo fileInfo)
   at FSharpLint.Application.Lint.lintParsedSource(OptionalLintParameters optionalParams, ParsedFileInformation parsedFileInfo)
   at FSharpLintVs.LintChecker.<DoUpdateAsync>d__48.MoveNext() --- End of stack trace from previous location where exception was thrown --- 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.ThreadingTools.<WithCancellationSlow>d__9.MoveNext() --- End of stack trace from previous location where exception was thrown --- 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FSharpLintVs.LintActionsSource.<>c__DisplayClass11_0.<<HasSuggestedActionsAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.<CallExtensionPointAsync>d__36`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by deviousasti** [comment]
Hello isral, thank you for reporting this..
A `MissingMethodException` usually means a different version of the assembly was loaded into VS.

Do you have any other F# related extensions installed?

**Comment by isral** [comment]
I don't think so, but I have Ionide-fsharp installed on VS Code.

**Comment by deviousasti** [comment]
That shouldn't be a problem.
I've published a newer version of F# lint with updated FCS, could you update and see if that resolves the issue?

**Comment by isral** [comment]
Sadly no.
Thank you.

**Comment by deviousasti** [comment]
Could you try using FusLogVwr or Fusion++ (https://github.com/awaescher/Fusion) to record the assembly fusion log? And post  the log for `FParsec `? We can find out exactly what's being loaded for `FParsec`.
